CREATE TABLE IF NOT EXISTS suppliers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact_person VARCHAR(255),
    phone VARCHAR(50),
    email VARCHAR(255),
    address TEXT,
    inn VARCHAR(20),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_suppliers_name_not_blank CHECK (BTRIM(name) <> '')
);

CREATE TABLE IF NOT EXISTS flowers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id INTEGER NOT NULL REFERENCES suppliers(id) ON DELETE RESTRICT,
    name VARCHAR(255) NOT NULL,
    variety VARCHAR(255),
    color VARCHAR(100),
    unit VARCHAR(50) NOT NULL,
    purchase_price NUMERIC(12, 2) NOT NULL,
    min_batch INTEGER NOT NULL,
    season VARCHAR(100),
    notes TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_flowers_name_not_blank CHECK (BTRIM(name) <> ''),
    CONSTRAINT ck_flowers_unit_not_blank CHECK (BTRIM(unit) <> ''),
    CONSTRAINT ck_flowers_purchase_price_positive CHECK (purchase_price > 0),
    CONSTRAINT ck_flowers_min_batch_positive CHECK (min_batch > 0)
);

CREATE TABLE IF NOT EXISTS contracts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_number VARCHAR(50) NOT NULL UNIQUE,
    contract_date DATE,
    customer_name VARCHAR(255) NOT NULL,
    customer_phone VARCHAR(50),
    customer_email VARCHAR(255),
    object_name VARCHAR(255) NOT NULL,
    object_address TEXT NOT NULL,
    start_date DATE,
    end_date DATE,
    price_coefficient NUMERIC(8, 2) NOT NULL DEFAULT 1.00,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_contracts_number_not_blank CHECK (BTRIM(contract_number) <> ''),
    CONSTRAINT ck_contracts_customer_not_blank CHECK (BTRIM(customer_name) <> ''),
    CONSTRAINT ck_contracts_object_not_blank CHECK (BTRIM(object_name) <> ''),
    CONSTRAINT ck_contracts_address_not_blank CHECK (BTRIM(object_address) <> ''),
    CONSTRAINT ck_contracts_price_coefficient_positive CHECK (price_coefficient > 0),
    CONSTRAINT ck_contracts_status_valid CHECK (status IN ('draft', 'active', 'completed', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS purchase_orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id INTEGER NOT NULL REFERENCES contracts(id) ON DELETE RESTRICT,
    flower_id INTEGER NOT NULL REFERENCES flowers(id) ON DELETE RESTRICT,
    quantity NUMERIC(12, 2) NOT NULL,
    unit_price_snapshot NUMERIC(12, 2) NOT NULL,
    line_amount NUMERIC(14, 2) NOT NULL,
    order_date DATE,
    planned_delivery_date DATE,
    actual_delivery_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'created',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_purchase_orders_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_purchase_orders_unit_price_snapshot_positive CHECK (unit_price_snapshot > 0),
    CONSTRAINT ck_purchase_orders_line_amount_positive CHECK (line_amount > 0),
    CONSTRAINT ck_purchase_orders_status_valid CHECK (status IN ('created', 'approved', 'ordered', 'delivered', 'cancelled'))
);
